# Generated by Django 3.2.13 on 2022-07-06 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=480)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('due_on', models.DateTimeField(blank=True)),
                ('completed_on', models.DateTimeField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('tasked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
