# Push updated files to my EC2 instance, then rebuild the docker containers
# Inspired by https://stackoverflow.com/a/66661512/6775693

name: CD

on:

jobs:
  deploy: Push to EC2 Instance
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "."
        TARGET: "~/test"

    - name: Recompose
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            ls
            cd ~/test
            ls
