# Push updated files to my EC2 instance, then rebuild the docker containers
# Inspired by https://stackoverflow.com/a/66661512/6775693

name: CD

on: push

jobs:
  deploy:
    name: Deploy & Recompose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "."
          TARGET: "~/todoSrc/todo"

      - name: Recompose
        uses: fifsky/ssh-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}
            user: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            command: |
              cd ~/todoSrc/todo
              docker compose -f production.yml down
              docker compose -f production.yml up --build -d
